# Series
A Series is very similar to a NumPy array (in fact it is built on top of the NumPy array object). What differentiates the NumPy array from a Series, is that a Series can have axis labels, meaning it can be indexed by a label, instead of just a number location. It also doesn't need to hold numeric data, it can hold any arbitrary Python Object.

In [111]:
import numpy as np
import pandas as pd

In [112]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array(my_list)
d ={'a':10, 'b':20, 'c':30}

In [113]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [114]:
pd.Series(data=my_list, index=labels)

a    10
b    20
c    30
dtype: int64

In [115]:
pd.Series(my_list, labels)

a    10
b    20
c    30
dtype: int64

In [116]:
#passing numpy array inside series
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [117]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

In [118]:
d

{'a': 10, 'b': 20, 'c': 30}

In [119]:
#dictionary passed into series
pd.Series(d)  #keys are used as index and values are used as data

a    10
b    20
c    30
dtype: int64

In [120]:
#series holding string data 
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [121]:
ser1 = pd.Series([1,2,3,4], ['USA','Germany','USSR','Japan'])

In [122]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [123]:
ser2 = pd.Series([1,2,5,4], ['USA','Germany','Italy','Japan'])

In [124]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [125]:
#accessing data through actual index values
ser1['USA']

np.int64(1)

In [126]:
ser1 + ser2  #where match value is not found NaN is returned

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

# DataFrames

DataFrames are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index.

In [127]:
from numpy.random import randn

In [128]:
#seeding to get same random numbers
np.random.seed(101)

In [129]:
randn(5,4)
#creating 2D numpy array of 5 rows and 4 columns

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [130]:
#df = pd.DataFrame(data,index,columns)
df =pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [131]:
df
#each column is a pandas series and sharing the common index

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [132]:
#accessing columns through column names, output will look like a series
# df['column name']   or df.column_name
df['W']

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [133]:
df.W

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [134]:
type(df['W'])

pandas.core.series.Series

In [135]:
type(df)

pandas.core.frame.DataFrame

In [136]:
#accessing multiple columns, output will look like a dataframe
# passinng a list of column names
df[['W','Z']]

          W         Z
A  0.302665 -1.159119
B -0.134841  0.184502
C  0.807706  0.329646
D -0.497104  0.484752
E -0.116773  1.996652

In [137]:
#adding a new column to the dataframe
df['new'] = df['W'] + df['Y']

In [138]:
df

          W         X         Y         Z       new
A  0.302665  1.693723 -1.706086 -1.159119 -1.403420
B -0.134841  0.390528  0.166905  0.184502  0.032064
C  0.807706  0.072960  0.638787  0.329646  1.446493
D -0.497104 -0.754070 -0.943406  0.484752 -1.440510
E -0.116773  1.901755  0.238127  1.996652  0.121354

In [139]:
df.drop('new',axis=1)  #drop the column named 'new', axis = 1 means we are dropping a column, axis = 0 means we are dropping a row

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [140]:
df.drop('A',axis=0)  #dropping a row, not happening inplace

          W         X         Y         Z       new
B -0.134841  0.390528  0.166905  0.184502  0.032064
C  0.807706  0.072960  0.638787  0.329646  1.446493
D -0.497104 -0.754070 -0.943406  0.484752 -1.440510
E -0.116773  1.901755  0.238127  1.996652  0.121354

In [141]:
#making inplace = True to make the changes permanent
df.drop('new',axis=1,inplace=True)

In [142]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [143]:
#background of axis 0 being row and axis 1 being column
df.shape
#in returned tuple, 0th index is row and 1st index is column

(5, 4)

In [144]:
#accessing row through loc and iloc
df.loc['A']

W    0.302665
X    1.693723
Y   -1.706086
Z   -1.159119
Name: A, dtype: float64

In [145]:
df.iloc[0]  #iloc is used for integer based indexing, so we pass the index of the row we want to access, in this case 0th index is A

W    0.302665
X    1.693723
Y   -1.706086
Z   -1.159119
Name: A, dtype: float64

In [146]:
#df.loc[row,column]
df.loc['B','Y']  #accessing value at row B and column Y

np.float64(0.16690463609281317)

In [147]:
df.loc[['A','B'],['W','Y']]

          W         Y
A  0.302665 -1.706086
B -0.134841  0.166905

In [148]:
#condition based selection
df > 0

       W      X      Y      Z
A   True   True  False  False
B  False   True   True   True
C   True   True   True   True
D  False  False  False   True
E  False   True   True   True

In [149]:
booldf = df > 0
booldf

       W      X      Y      Z
A   True   True  False  False
B  False   True   True   True
C   True   True   True   True
D  False  False  False   True
E  False   True   True   True

In [150]:
df [booldf]

          W         X         Y         Z
A  0.302665  1.693723       NaN       NaN
B       NaN  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D       NaN       NaN       NaN  0.484752
E       NaN  1.901755  0.238127  1.996652

In [151]:
df[df>0]

          W         X         Y         Z
A  0.302665  1.693723       NaN       NaN
B       NaN  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D       NaN       NaN       NaN  0.484752
E       NaN  1.901755  0.238127  1.996652

In [152]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [153]:
df['W'] > 0

A     True
B    False
C     True
D    False
E    False
Name: W, dtype: bool

In [154]:
#will display only column A and C
df[df['W']>0]

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [155]:
#grabbing all the dataframe where 'Z' is less than 0
df[df['Z']>00]

          W         X         Y         Z
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [156]:
#storing the resulting df
resultdf = df[df['W']>0]
resultdf

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [157]:
resultdf['X']

A    1.693723
C    0.072960
Name: X, dtype: float64

In [158]:
df[df['W']>0]['X']

A    1.693723
C    0.072960
Name: X, dtype: float64

In [159]:
df[df['W']>0][['X','Y']]

          X         Y
A  1.693723 -1.706086
C  0.072960  0.638787

In [160]:
#spltting df[df['W']>0][['X','Y']]
boolser = df['W']>0
result = df[boolser]
mycols = ['X','Y']
result[mycols]

          X         Y
A  1.693723 -1.706086
C  0.072960  0.638787

In [161]:
#passing double condition
#wont work: df[(df['W']>0) and (df['Y']>1)]     'and' should be replaced with & and each condition should be in brackets
df[(df['W']>0) & (df['Y']<0)]

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119

In [162]:
df[(df['W']>0) | (df['Y']<0)]  #or operation

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752

In [164]:
#resetting the index to integer based index
df.reset_index(inplace=False)

  index         W         X         Y         Z
0     A  0.302665  1.693723 -1.706086 -1.159119
1     B -0.134841  0.390528  0.166905  0.184502
2     C  0.807706  0.072960  0.638787  0.329646
3     D -0.497104 -0.754070 -0.943406  0.484752
4     E -0.116773  1.901755  0.238127  1.996652

In [165]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [166]:
#creating list using split function for new index
newind = 'CA NY WY OR CO'.split()
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [167]:
df['State'] = newind

In [168]:
df

          W         X         Y         Z State
A  0.302665  1.693723 -1.706086 -1.159119    CA
B -0.134841  0.390528  0.166905  0.184502    NY
C  0.807706  0.072960  0.638787  0.329646    WY
D -0.497104 -0.754070 -0.943406  0.484752    OR
E -0.116773  1.901755  0.238127  1.996652    CO

In [169]:
#making a column as index
df.set_index('State')

              W         X         Y         Z
State
CA     0.302665  1.693723 -1.706086 -1.159119
NY    -0.134841  0.390528  0.166905  0.184502
WY     0.807706  0.072960  0.638787  0.329646
OR    -0.497104 -0.754070 -0.943406  0.484752
CO    -0.116773  1.901755  0.238127  1.996652

## Multi-Index and Index Hierarchy

In [170]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [171]:
list(zip(outside,inside))

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [172]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

             A         B
G1 1 -0.993263  0.196800
   2 -1.136645  0.000366
   3  1.025984 -0.156598
G2 1 -0.031579  0.649826
   2  2.154846 -0.610259
   3 -0.755325 -0.346419

In [173]:
df.loc['G1']

          A         B
1 -0.993263  0.196800
2 -1.136645  0.000366
3  1.025984 -0.156598

In [174]:
df.loc['G1'].loc[1]

A   -0.993263
B    0.196800
Name: 1, dtype: float64

In [175]:
df.index.names

FrozenList([None, None])

In [176]:
df.index.names = ['Group','Num']

In [177]:
df

                  A         B
Group Num
G1    1   -0.993263  0.196800
      2   -1.136645  0.000366
      3    1.025984 -0.156598
G2    1   -0.031579  0.649826
      2    2.154846 -0.610259
      3   -0.755325 -0.346419

In [178]:
df.loc['G2'].loc[2]['B']

np.float64(-0.6102588558227414)

In [180]:
df.xs('G1')

            A         B
Num
1   -0.993263  0.196800
2   -1.136645  0.000366
3    1.025984 -0.156598

In [179]:
df.xs(1,level='Num')

              A         B
Group
G1    -0.993263  0.196800
G2    -0.031579  0.649826

# Missing Data

In [183]:
d = {'A':[1,2,np.nan], 'B':[5,np.nan,np.nan],'C':[1,2,3]}

In [184]:
d

{'A': [1, 2, nan], 'B': [5, nan, nan], 'C': [1, 2, 3]}

In [185]:
df =pd.DataFrame(d)

In [186]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [188]:
#dropping missing values from a dataset
#will drop any row which has at least one missing value, by default axis is 0, so we are dropping rows, if we want to drop columns we will have to specify axis = 1
df.dropna()

     A    B  C
0  1.0  5.0  1

In [189]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.dropna(axis=1)   #will drop column

   C
0  1
1  2
2  3

In [191]:
#thresholding the data, will drop rows which have less than 2 non-NA values
df.dropna(thresh=2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [193]:
df.fillna(value='FILL ')  #filling the null with a value

       A      B  C
0    1.0    5.0  1
1    2.0  FILL   2
2  FILL   FILL   3

In [194]:
#filling column A with its mean
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

# Groupby

The groupby method allows you to group rows of data together and call aggregate functions

In [195]:
# Create dictionary
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [196]:
df = pd.DataFrame(data)

In [200]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [201]:
#groupby Company column('df.groupby('column name')')
byComp = df.groupby('Company')

In [203]:
#aggregation
byComp['Sales'].mean()

Company
FB      296.5
GOOG    160.0
MSFT    232.0
Name: Sales, dtype: float64

In [206]:
#groupby the column Company and then aggragation performed on the Sales column
df.groupby('Company')['Sales'].mean()

Company
FB      296.5
GOOG    160.0
MSFT    232.0
Name: Sales, dtype: float64

In [208]:
m = df.groupby('Company')['Sales'].sum()

In [209]:
m

Company
FB      593
GOOG    320
MSFT    464
Name: Sales, dtype: int64

In [ ]:
#because of single bracket, it is a series
type(m)

pandas.core.series.Series

In [211]:
m = df.groupby('Company')[['Sales']].sum()

In [214]:
print(type(m))
m

<class 'pandas.core.frame.DataFrame'>

         Sales
Company
FB         593
GOOG       320
MSFT       464

In [215]:
m

         Sales
Company
FB         593
GOOG       320
MSFT       464

In [216]:
m.loc['FB']

Sales    593
Name: FB, dtype: int64

In [217]:
df.groupby('Company').max()

          Person  Sales
Company
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [219]:
df.groupby('Company').min()

          Person  Sales
Company
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [221]:
df.groupby('Company')[['Sales']].std()

              Sales
Company
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [222]:
df.groupby('Company').describe()

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [223]:
df.groupby('Company').describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000